version: '3'
services:
  jenkins:
    container_name: jenkins
    build: .
    #    image: jenkins:jenkins
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - /test/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:
